DocGen4/Output/Base.lean, DocGen4/Output/Inductive.lean, DocGen4/Output/Module.lean, DocGen4/Output/Structure.lean, DocGen4/Process.lean, static/style.css
=> Structure support

DocGen4/Output/Inductive.lean, DocGen4/Output/Structure.lean, DocGen4/Process.lean
=> Fix links to inductive constructors and structure fields

DocGen4/Process.lean
Previously we would print all names with macro scopes (after removing
the macro related stuff) which could cause confusion if for example
there was an actual parameter named `a` and one named `a` but
autogenerated by Lean itself. Now we only try to print names with
macro scopes iff they are names of type class parameters. Otherwise
the rest of the Expr is moved behind the :.
=> fix: Printing of argument names with macro scopes

DocGen4/Output/Module.lean, DocGen4/Process.lean, lean-toolchain
=> imports, imported by

DocGen4/Output/Structure.lean, lean-toolchain, static/style.css
Add the ability to show customly named structure constructors.
Closes: #23
=> feat: Custom structure ctors

DocGen4/Output.lean, DocGen4/Output/Base.lean, DocGen4/Output/Find.lean, DocGen4/Output/Semantic.lean, DocGen4/Output/Template.lean, static/declaration-data.js, static/find/find.js, static/how-about.js, static/mathjax-config.js, static/nav.js, static/search.js, static/site-root.js, static/tactic.js
In this pr I'll refactor the JavaScript part to more maintainable one, as well as implement the find and src feature.
Closes: #30
=> Windows find support

DocGen4/Load.lean, DocGen4/Output.lean, Main.lean, lakefile.lean, lean-toolchain
=> Lake integration

DocGen4/Output.lean, DocGen4/Output/Base.lean, DocGen4/Output/Find.lean, DocGen4/Output/Template.lean, static/declaration-data.js, static/find/find.js, static/search.js
This addresses the issues caused by #39 as described at the end of the discussion in #39. The fix is certainly not pretty since it's using global variables, but my JS knowledge is limited and I wanted to push out a quick fix.
@xubaiw might want to chime in and fix the mess I left when he has time :wink:
=> Fix search

DocGen4/Output/Definition.lean, DocGen4/Output/Inductive.lean, DocGen4/Output/Module.lean, DocGen4/Output/Navbar.lean, DocGen4/Output/Structure.lean, DocGen4/Output/Template.lean, DocGen4/ToHtmlFormat.lean
=> refactor: use `rawIdent`

DocGen4/Load.lean, DocGen4/Process/Attributes.lean, DocGen4/Process/Base.lean, lakefile.lean, lean-toolchain
Waiting for https://github.com/mhuisi/lean4-cli/pull/9
=> Update to latest nightly

DocGen4/Output/Inductive.lean, Main.lean, static/style.css
=> feat: Inductive constructor doc strings

DocGen4/Process/Hierarchy.lean, lakefile.lean
With is, one can now do:
```shell
lake build Foo.Bar:docs
```
To build the documentation of module `Foo.Bar` (in any package sharing a workspace with doc-gen4). Currently this is rather slow (since loading a lakefile and ensuring doc-gen4 is built just to build one html file is not super efficient). The code is also rather messy due to the very unintuitive state of the current internal Lake API. However, it is a good PoC of what I would like to achieve. That is, building documentation with a simple Lake invocation.
=> feat:  experimental module facet for producing docs

lakefile.lean
I didn't even know one could import modules from executables! Not sure how to feel about that.
=> chore: drop unused import

DocGen4/LeanInk/Process.lean, DocGen4/Output/DocString.lean, DocGen4/Output/Inductive.lean, DocGen4/Output/Module.lean, DocGen4/Output/Structure.lean, DocGen4/Output/ToHtmlFormat.lean, DocGen4/Process/Attributes.lean, DocGen4/Process/Hierarchy.lean, lakefile.lean, lean-toolchain
I did not update the manifest, so this PR may not build until the upstream dependencies merge their respective bump PRs.
=> chore: update toolchain 10-20

DocGen4/Output/Template.lean, static/style.css
Made minor changes to spacing. Fixed the accumulation of slashes when using the nav links and fixed the scroll bar not appearing. Also changed the search link to mathlib4_docs instead of mathlib_docs.
=> fix: minor style improvements

.github/workflows/build.yml, DocGen4/Output/Base.lean, DocGen4/Output/Navbar.lean, lean-toolchain
=> Short names

.github/workflows/mathlib4docs.yml, DocGen4/Output/Index.lean, deploy_docs.sh, lake-manifest.json, test_docs.sh
This is the approach suggested by James Gallicchio, let's hope this works!
=> feat: new CI setup

DocGen4/Output/Index.lean
=> fix: properly comment out for the workaround

DocGen4/Load.lean
Now that Lake is officially part of the core, it seems worthwhile to include it in the core docs.
=> feat: include Lake as part of the core docs

DocGen4/Output/Module.lean, static/style.css
=> feat: docs below names

README.md
Correct the path to the root of the built docs.
=> doc: fix path to root of docs

DocGen4/Output/Template.lean, static/style.css
Also added a missing `<span>` tag around "Documentation" in the header.
=> Fix over-aggressive hiding of file path in header

lakefile.lean, lean-toolchain
Includes some style touchups using new / overlooked Lake utilities.
=> chore: update Lean/Lake to v4.8.0-rc1

DocGen4/LeanInk/Output.lean, DocGen4/Output.lean, DocGen4/Output/Base.lean, DocGen4/Process/Hierarchy.lean, lakefile.lean, static/favicon.svg
This PR adds the favicon as doc-gen3.
=> feat: add favicon

DocGen4/Output/Base.lean, DocGen4/Output/DocString.lean, DocGen4/Output/Navbar.lean, DocGen4/Output/ToHtmlFormat.lean
Reverts leanprover/doc-gen4#190
=> Revert "fix: escape html correctly"

README.md
People seem to be converging on a mathlib4_docs-but-nested style setup https://github.com/leanprover-community/mathlib4_docs due to issues with the currently recommended one
Document this as the new recommended setup.
=> doc: mathlib4_docs style setup

lake-manifest.json
This should improve reference page rendering. See also https://github.com/dupuisf/BibtexQuery/issues/7.
=> feat: bump BibtexQuery version

DocGen4/Output/Base.lean
=> fix: correctly split whitespace

DocGen4/Output/DocString.lean, lake-manifest.json
Use new encoding for general categories.
=> fix: patch for UnicodeBasic v1.2.0
