leanprover/doc-gen4

DocGen4/Output.lean, DocGen4/Output/Base.lean, DocGen4/Output/Module.lean
The current implementation is only capable of linking declarations right from the package that is being documented, there
are two other cases possible that are not handled yet:
1. Declarations that are coming from `Init`, `Std` or `Lean` aka the compiler itself, this should be addressable by obtaining the
compiler revision and linking to the compiler repository if the declaration is coming from one of those modules
2. Modules that are pulled in as dependencies through Lake, for this case it is probably possible to obtain the URLs and revisions based on the Lakefile and link to those instead.
This implementation only deals with the first as this can deal perfectly fine with mathlib since it has no dependencies apart from the compiler
=> Basic source links

DocGen4/Output/Inductive.lean, DocGen4/Output/Navbar.lean, DocGen4/ToHtmlFormat.lean, Main.lean, static/style.css
When browsing mathlib4_docs, the first thing that jumps into the eye is the duplicate module names on the left side.  This PR removes the header, which is one of the duplicates.
I've also taken the liberty of extending the `<div>[children]</div>` syntax to attributes (i.e., `<div [attributes] />`) since that simplifies the navbar code quite a bit.
=> fix: do not show top-level modules twice in navbar

DocGen4/Output/Navbar.lean, DocGen4/ToHtmlFormat.lean, static/style.css
Currently non leaf modules are ignored in sidebar navigation.
This PR fixes this problem, like this:
=> fix: add nav link to non leaf node modules

DocGen4/Output/Base.lean, DocGen4/Output/Definition.lean, DocGen4/Output/Module.lean, DocGen4/ToHtmlFormat.lean
This PR:
- implements escaping in the `CodeWithInfos` linkifier
- implements an upper limit for equation length
Closes: #35
=> Better equations

DocGen4/Output.lean, DocGen4/Output/Base.lean, Main.lean, README.md, deploy_docs.sh
Based on a discussion with @hargoniX , we decided it is simpler to manually calculate the offset to the root when generating relative paths. This supersedes #32 , which calculates nesting depth by normalizing paths via `unsafePerformIO`+`realpath`.
=> Add support for relative paths

static/find/find.js
[As reported on Zulip.](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Boolean.20and.2For.20etc)
=> Work around unsupported RegExp lookbehind in WebKit.

DocGen4/Output/Navbar.lean, DocGen4/Output/Template.lean
So apparently a javascript thing cannot access an iframe's HTML...that makes sense.
Close: #96
=> fix: save the expansion state of the tree again

DocGen4/Output.lean, DocGen4/Output/Search.lean, DocGen4/Output/Template.lean, DocGen4/Process/Hierarchy.lean, lakefile.lean, static/declaration-data.js, static/search.js, static/style.css
Now instead of clicking the "Google Site Search"' button, the user has the option of clicking the "Search" button, which will take them to a results page. Currently, the results are identical to the autocomplete results, but the number of results is not limited to 30.  In the future, more information and search options could be added to this page to make a more powerful search.
Fixes #107
=> Add a search page to the docs.

static/style.css
ref #105
I just allowed wrapping and added a line break after `decl_name`.
It looks nice on narrow screens too:
=> fix implicit arg wrapping

DocGen4/Output/Base.lean, DocGen4/Output/Module.lean, DocGen4/Output/Template.lean
ref #100
`.break_within` requires unbreakable `.name` parts inside:
```css
.break_within .name {
word-break: normal;
}
```
so I added them in all places where `break_within` is used.
=> linebreaks at `.` in names

DocGen4/Output/DocString.lean
Equality of `Unicode.GeneralCategory` does not always do what you expect, use `Unicode.isInGeneralCategory` instead. For example:
```lean
#eval Unicode.isInGeneralCategory '.' Unicode.GeneralCategory.P -- true
#eval Unicode.getGeneralCategory '.' == Unicode.GeneralCategory.P -- false!!!
```
=> fix: correct character category testing

DocGen4/Output/DocString.lean, lake-manifest.json, lakefile.lean
The original library name was ill chosen, so I rebranded. Apologies for the inconvenience.
=> fix: unicode dependency

DocGen4/Output/DocString.lean
=> fix: Use Z(separator) instead of S(ymbol) category

DocGen4/Output/Module.lean
Some defs such as [Lean.RBTree](https://leanprover-community.github.io/mathlib4_docs/Lean/Data/RBTree.html#Lean.RBTree) have instances, this PR adds the "Instances For" dropdown for defs also so we can see them in docs: e.g. in this case this displays as
```
def [Lean.RBTree](http://localhost:1000/Lean/Data/RBTree.html#Lean.RBTree) (α : [Type](http://localhost:1000/foundational_types.html) u) (cmp : α → α → [Ordering](http://localhost:1000/Init/Data/Ord.html#Ordering)) :
[Type](http://localhost:1000/foundational_types.html) u
Equations
Instances For
[Lean.instInhabitedRBTree](http://localhost:1000/Lean/Data/RBTree.html#Lean.instInhabitedRBTree)
[Lean.instEmptyCollectionRBTree](http://localhost:1000/Lean/Data/RBTree.html#Lean.instEmptyCollectionRBTree) …
```
=> feat: list instances for defs also

test_docs.sh
By using rsync in place of cp for more control
The .git folders were causing issues for me (permissions failed for some packed objects on mac) but not copying them seems generally sensible.
=> feat: don't copy .git folders in test

static/search.js
Previously if the user typed something before the data loads and the event handler is added after they would have no way of knowing when the data was loaded and is actually ready to start searching. This plays a role now for mathlib where the data takes a nontrivial amount of time to load.
=> feat: trigger search input when event handler is added

DocGen4/Output.lean, DocGen4/Output/Base.lean, DocGen4/Output/Navbar.lean, DocGen4/Process/Hierarchy.lean, lakefile.lean, static/color-scheme.js, static/style.css
This commit adds a dark mode to doc-gen4. It takes much inspiration from leanprover-community/doc-gen#160.
Unlike the dark theme in doc-gen, this will work with or without javascript. If javascript is disabled, the color picker will not work. However, the correct theme will be detected from the browser based on css media queries.
If javascript is enabled, the color picker will work and color picker preferences will be remembered.
note: a dark-mode is not added to inked code. This PR only applies to generated documentation.
closes #117
=> add dark mode

lakefile.lean, lean-toolchain
Updates the lakefile to no longer need the workaround (which is now broken) due to a Lake update. 
(**EDIT**: Now just a refactor with the new main change.)
=> chore: update to new Lean/Lake version

lean-toolchain
I wouldn't usually send a bump PR, but `nightly-2023-08-19` is now a tentative release candidate for the first official release of Lean 4, and it would be nice to have everything explicitly test it out!
=> chore: update toolchain

DocGen4/Output/DocString.lean
When linkifying code blocks in markdown comments we check that the language of the code block isn't explicitly set to something other than Lean.
E.g.
````
```julia
add(1, 1)
```
````
should not link to the lean definition of `add` in the docs.
We do this by checking that any `class` attribute of the form `language-...` on the code block is `language-lean` (or that there are none, so the default remains that code blocks are lean code)
=> feat: only linkify lean code

lean-toolchain
Usually, the tags are named with a prefixed v. The same is true for the current releases
=> [fix] wrong lean-toolchain version

DocGen4/Output/DocString.lean
mathlib often references other files in docstrings, e.g. in https://leanprover-community.github.io/mathlib4_docs/Mathlib/Analysis/Normed/Group/Basic.html#AddMonoidHomClass.lipschitz_of_bound :
It would be helpful if those turned into links.
=> feat: autolink references to files

DocGen4/Output.lean, DocGen4/Output/Base.lean, DocGen4/Output/Template.lean, DocGen4/Process/Hierarchy.lean, lakefile.lean, static/expand-nav.js
Pure javascript implementation of a nice feature we used to have in doc-gen3, automatically opening the navigation tree leading to the current file (and italicise the current filename). Closes #106.
=> feat: expand the current file in the navbar

static/declaration-data.js, static/find/find.js
Even though the result of `fetchCachedDeclarationData` was ignored due to #133, we were still performing the request, which takes some time on FF to deserialize (or something), depending on what happened to be on the user's cache (because the cache is never written to, only read). This moves the disabling earlier, so that the cache is not read at all (since this means deserializing an old version of the mathlib JSON data, then ignoring it and fetching another version of the mathlib JSON data).
Also fixes an issue where the `undefined` pattern is passed to `decodeURIComponent` (resulting in `"undefined"` which is mishandled by subsequent code).
=> fix: don't fetch unused cache, FF fixes

DocGen4/Output/DocString.lean, DocGen4/Output/ToHtmlFormat.lean
also fix the escape codes
see https://leanprover-community.github.io/mathlib4_docs/Mathlib/Order/ConditionallyCompleteLattice/Basic.html#ciSup_le for examples of why this is needed
=> feat: html escape docstrings

DocGen4/Output.lean, DocGen4/Output/SourceLinker.lean, DocGen4/Output/ToJson.lean, Main.lean, README.md, lakefile.lean
This makes some changes to source code url resolution to allow `vscode://file/` urls.  I find this useful for quickly jumping to the source code when browsing locally generated documentation.
This changes the default is to use VSCode urls if the git repo has changed.  This may not be the right approach.  We could further generalize how resolution occurs, but  I thought I'd submit the PR and start a discussion.
=> feat: Add support for `vscode://file/` source links

DocGen4/Output/Index.lean, DocGen4/Output/Module.lean, DocGen4/Output/Template.lean, static/style.css
* Visual hierarchy of the `h1, h2`, etc. elements is important. I remove the `17px` fixed `font-size` for section title elements and adjust code `font-size` to a relative `92%`. I also adjust the spacing a little.
* ~~Mention `mathlib4` on the home page. Add link to point to community page and `mathlib3` docs.~~
* ~~The biggest text on the top left should be `Mathlib4` rather than the non-descriptive `Documentation`. Size adjusted to `h2`.~~
* The file name shown at the top is now grey to reduce visual fatigue. Size adjusted to `h2`, centre aligned. Line height changed to 95% to fit better when wrapped.
* Fixed a couple typos, where `.header` is used in the CSS selector instead of `header`.
* Replace the repeated file name on the top right with a "return to top" link.
=> Remove fixed font-size

DocGen4/Output/DocString.lean
This PR fixes `<url>` processing problem of markdown introduced by #157. It turns out that the problem occurred at `Lean.Xml.instToStringElement` which does not do escape. The code is copied from `Lean.Xml.instToStringElement` with escape code added. The added functions should be removed once https://github.com/leanprover/lean4/issues/4411 is fixed.
discussion: <https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Contribution.20to.20doc-gen4.3F/near/443537944>
=> fix: `<url>` processing of markdown

README.md, lake-manifest.json
Newest version of md4lean compiles on Windows. I'd like to update md4lean version and README and states that it compiles on Windows.
=> chore: update md4lean version and README that it compiles on Windows

DocGen4/Output/Template.lean
Recently, polyfill.io, a well-known service for dynamically supplying polyfills for various browsers, has been the target of a supply chain attack. Numerous security researchers have confirmed the presence of malicious code within the JavaScripts provided by polyfill.io. This pull request proposes an alternative service URL from Cloudflare to replace the compromised domain.
References:
- https://blog.qualys.com/vulnerabilities-threat-research/2024/06/28/polyfill-io-supply-chain-attack
- https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
=> Update Template.lean to remove poisioned polyfill.io

DocGen4/Output/Module.lean, DocGen4/Process/Base.lean, DocGen4/Process/NameInfo.lean
This PR makes use of the core signature delaborator to pretty print signatures. This fixes some bugs and brings the output in line with `#check`.
For example:
- Now binders are grouped.
- Now it uses the same heuristics as `#check` for what comes before and after the colon.
- Now the bug [reported in this Zulip thread](https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/docgen.20strange.20daggers/near/481964331) is fixed, where daggers appeared in the incorrect positions.
=> feat: use the core signature delaborator

DocGen4/Output/Structure.lean, DocGen4/Process/Base.lean, DocGen4/Process/DocInfo.lean, DocGen4/Process/StructureInfo.lean, static/style.css
- The precise list of parent structures is shown, now that Lean records this information. Closes #223
- Fixes an issue where fields of a structure wouldn't be shown. Closes #229
- Grays out inherited fields and gives them a link to their definitions.
- Fixes an issue where inherited fields would have an id attribute with a synthetic name, which could cause links to go to the wrong place. Now inherited fields don't have an id attribute.
=> feat: improvements to `structure` output

DocGen4/Process/StructureInfo.lean
The calculation for projection functions was incorrect for fields that came from parents that overlapped with another. It was using the projection function that Lean uses to access the field, not the actual origin projection function.
=> fix: have inherited fields link to their actual origin

DocGen4/Load.lean
See https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/lean4checker.20failure/near/486823143 for more details.
If initializers don't run, then the parsers registered with `initlialize add_parser_alias ..` do not run, and so the alias never exists and the downstream code that references the alias crashes.
`import-graph` and the Batteries linter framework already include this line.
I have not tested if this actually resolves the mathlib build issue,
=> fix: resolve build issues with mathlib

DocGen4/Process/DocInfo.lean, DocGen4/Process/InstanceInfo.lean
=> fix: re-support Prop valued instances

static/style.css
These are particularly nasty when they appear in code blocks.
Fixes #165
=> fix: do not insert extra indents inside constructor docstrings

DocGen4/Output/Arg.lean, DocGen4/Output/Inductive.lean, DocGen4/Output/Module.lean, DocGen4/Process/Base.lean, DocGen4/Process/InductiveInfo.lean, static/style.css
=> feat: show inductive constructor argument names

DocGen4/Process/Base.lean, DocGen4/Process/DocInfo.lean, DocGen4/Process/OpaqueInfo.lean
The primitives are displayed as `opaque`, matching the current documentation.
=> feat: show documentation for Quot primitives

DocGen4/Output/Structure.lean, DocGen4/Process/Base.lean, DocGen4/Process/NameInfo.lean, DocGen4/Process/StructureInfo.lean, static/style.css
=> feat: show structure field argument names

test_docs.sh
This can only be merged after #[6374](https://github.com/leanprover/lean4/issues/6374) is fixed.
=> chore: make CI fail if we panic

DocGen4/Process/NameInfo.lean
This PR renders signatures in the namespace of the declaration, which causes non-protected names in that namespace or any parent namespace to be abbreviated. The result is shorter signatures which can be much easier to read, though this could potentially be confusing for users who do not have the namespace open.
Before:
After:
=> feat: abbreviate names based on the namespace of the declaration

DocGen4/Output/Base.lean
Fixes a bug caused by a bug in https://github.com/leanprover/lean4/pull/6730 that causes `infoFormatToHtml` to add nested anchor tags, with many of the outer links being unwanted. This PR modifies `infoFormatToHtml` to avoid wrapping HTML in anchor tags if the HTML already contains one.
This is an improvement on its own, but we will also address the root cause in a Lean PR.
=> fix: prevent double anchoring

DocGen4/Output/Base.lean
This matches how lean file names are not escaped.
=> fix: do not escape module names for html files

DocGen4/Output/Base.lean
`withExtension` will try to strip any existing extension, but in this case we know there is not one to strip.
=> fix: support filenames with dots

DocGen4/Process/Analyze.lean, DocGen4/Process/Base.lean, DocGen4/Process/DefinitionInfo.lean, DocGen4/Process/DocInfo.lean, DocGen4/Process/InstanceInfo.lean, README.md
This PR allows generation of equations for definitions to be optionally disabled by an environment flag.
Zulip discussion here: [#lean4 > doc-gen4 Equations @ 💬](https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/doc-gen4.20Equations/near/519599099)
Supersedes #283.
=> feat: add option to disable equation generation for definitions via the AnalyzeM monad

DocGen4/Output/Base.lean
This has no visible effect, but will impact #286, and also saves one join.
=> chore: remove stray dot from internal paths

static/expand-nav.js
When the page loads, center the scrollbar on the left on the current module:
This should make it easier to navigate documentation for large projects like mathlib4. 
Also, I made its name slightly more distinguished than just using italic type.
=> Center the current module in expand-nav.js

DocGen4/Output/Module.lean, DocGen4/Process/Base.lean, DocGen4/Process/DefinitionInfo.lean, DocGen4/Process/DocInfo.lean, DocGen4/Process/NameInfo.lean, DocGen4/Process/TheoremInfo.lean, static/style.css
This is work in progress to add one of the two features discussed in #270, namely to highlight direct uses of sorry.
Transitive/implicit depending on `sorryAx` is not done, my naive approach for doing that was way to recursive and slowing things down too much, as [discussed on Zulip](https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/can.20doc-gen4.20show.20sorry-dependency.3F/near/541916787).
An example for what the result looks like can be seen at https://m4lvin.github.io/lean4-pdl/docs/Pdl/PartInterpolation.html#Cluster-tools
=> highlight direct use of sorry
